Add the syn flag for syn the tc_sram
KULeuven-MICAS/cluster_icache pull request #1
Opened 2024-09-19 11:52 UTC by Konste11ation

This PR adds the required flag for the synthesis flow.
Compared with the old local snitch_icache, this new one has already implemented the tc_sram as the memory. Hence we do not need to manually add the `snitch_icache_data.sv` and `snitch_icache_tag.sv`.

2024-09-19 11:56 UTC, rgantonio requested changes
Please add the `icache_data_mem` and the `icache_tag_mem` from the SNAX cluster first. It will save you time for the Hemaia too!!!

2024-09-19 12:29 UTC, rgantonio approved these changes
Are these the only changes you need? 😄

2024-09-19 12:29 UTC, rgantonio commented on src/snitch_icache_lookup_parallel.sv
> +  // end
Don't forget to clean these comments later on.

2024-09-19 12:29 UTC, rgantonio commented on src/snitch_icache_tag.sv
> +endmodule
Add new line! So github is clean.

2024-09-19 12:29 UTC, rgantonio commented on src/snitch_icache_data.sv
> +endmodule
Add new line so github is clean!

2024-09-19 12:31 UTC, Konste11ation commented on src/snitch_icache_data.sv
> +endmodule
In the `snitch_icache_lookup_serial.sv` there are also tc_sram_impl, but this file is not used in both occamy and snitch, we can safely ignore that

2024-09-19 14:35 UTC, rgantonio approved these changes
Seems good! Maybe after push double check on your PR in SNAX first.

https://github.com/KULeuven-MICAS/snax_cluster/pull/339

2024-09-20 08:05 UTC, rgantonio commented
There's no CI for this isn't there? let's try to get this in soon 😄 

@Konste11ation

2024-09-20 08:29 UTC, merged